window.taskDBImport = [
    {
        name: "CallMum",
        text: "Call Your Mum",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats",
        text: "Feed The Cats",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You grab the can of cat food and go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash",
        text: "Take Out Trash",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast",
        text: "Make Breakfast",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy it's full.",
        storyText: "You go to the kitchen to prepare some food",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes",
        text: "Do The Dishes",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy they are clean.",
        storyText: "You grab your sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap",
        text: "Fill Dish Soap",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of dish soap",
        resolutionText: "Your dish soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries",
        text: "Get Groceries",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You open the refrigerator and realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You walk to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash",
        text: "Pick Up Trash",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "DoHomework",
        text: "Do Your Homework",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You remember you have Game 251 homework due tonight",
        resolutionText: "The professor is so happy you completed your homework.",
        storyText: "You start up your computer to work on your homework",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TPSReport",
        text: "Complete The TPS Report",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You realize you never put the new coversheet on the TPS report you submitted at work",
        resolutionText: "Your TPS report is so happy to have a coversheet.",
        storyText: "You go to add the coversheet to the report",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeShower",
        text: "Take A Shower",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You smell a foul odor and realize it's you",
        resolutionText: "Your nose is so happy you're clean.",
        storyText: "You turn on the shower to let the water heat up",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetDressed",
        text: "Get Dressed",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You look down and realize you're still wearing your pajamas, the ones with the rubber duckies",
        resolutionText: "Your body misses its comfortable uniform but it will manage.",
        storyText: "You go to the closet to pick out an outfit",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "BrushTeeth",
        text: "Brush Your Teeth",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your teeth are feeling a little grimy",
        resolutionText: "Your teeth are so happy to be brushed.",
        storyText: "You grab your toothbrush and put on some toothpaste",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "StyleHair",
        text: "Style Your Hair",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have bed head",
        resolutionText: "Your hair is so happy to be styled.",
        storyText: "You find your comb and work wonders with your hair",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "WalkDog",
        text: "Walk The Dog",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You hear your dog whining",
        resolutionText: "Your dog is so happy to be outside.",
        storyText: "You grab the leash to take the dog for a walk",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GoRun",
        text: "Go For A Run",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You realize it's been a few days since you last worked out",
        resolutionText: "Your body is so happy to be alive.",
        storyText: "You put on your workout clothes and get ready for a run",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "CallMum3",
        text: "Call Your Mum3",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats3",
        text: "Feed The 3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash3",
        text: "Take Out Trash3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast3",
        text: "Make Breakfast3",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes3",
        text: "Do The Dishes3",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap3",
        text: "Fill Dish Soap3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries3",
        text: "Get Groceries3",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash3",
        text: "Pick Up Trash3",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "CallMum4",
        text: "Call Your Mum4",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats4",
        text: "Feed The Cats4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash4",
        text: "Take Out Trash4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast4",
        text: "Make Breakfast4",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes4",
        text: "Do The Dishes4",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap4",
        text: "Fill Dish Soap4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries4",
        text: "Get Groceries4",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash4",
        text: "Pick Up Trash4",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
]
