window.taskDBImport = [
    {
        name: "CallMum",
        text: "Call Your Mum",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats",
        text: "Feed The Cats",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash",
        text: "Take Out Trash",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast",
        text: "Make Breakfast",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes",
        text: "Do The Dishes",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap",
        text: "Fill Dish Soap",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries",
        text: "Get Groceries",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash",
        text: "Pick Up Trash",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "CallMum1",
        text: "Call Your Mum1",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats1",
        text: "Feed The Cats1",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash1",
        text: "Take Out Trash1",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast1",
        text: "Make Breakfast1",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes1",
        text: "Do The Dishes1",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap1",
        text: "Fill Dish Soap1",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries1",
        text: "Get Groceries1",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash1",
        text: "Pick Up Trash1",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "CallMum3",
        text: "Call Your Mum3",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats3",
        text: "Feed The 3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash3",
        text: "Take Out Trash3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast3",
        text: "Make Breakfast3",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes3",
        text: "Do The Dishes3",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap3",
        text: "Fill Dish Soap3",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries3",
        text: "Get Groceries3",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash3",
        text: "Pick Up Trash3",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "CallMum4",
        text: "Call Your Mum4",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats4",
        text: "Feed The Cats4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash4",
        text: "Take Out Trash4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast4",
        text: "Make Breakfast4",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy its full.",
        storyText: "You go to the kitchen to make breakfast",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes4",
        text: "Do The Dishes4",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy their clean.",
        storyText: "You grab you sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap4",
        text: "Fill Dish Soap4",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of soap",
        resolutionText: "Your soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries4",
        text: "Get Groceries4",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You run to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash4",
        text: "Pick Up Trash4",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
]