window.taskDBImport = [
    {
        name: "CallMum",
        text: "Call Mum",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know you need to call your mom",
        resolutionText: "Your mum is so happy you called.",
        storyText: "You pick up the phone and speed dial your mom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FeedCats",
        text: "Feed The Cats",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your cats are rubbing up against your legs, a tell tale sign they are hungry",
        resolutionText: "Your cats are so happy you fed them.",
        storyText: "You grab the can of cat food and go to feed the cats",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeOutTrash",
        text: "Take Out Trash",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You hear the trash truck down the street",
        resolutionText: "The truck stops to pick up your neighbors trash.  Just in time!",
        storyText: "You run to the garage to roll out the trash can",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBreakfast",
        text: "Make Breakfast",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your stomach is growling at you something fierce",
        resolutionText: "Your belly is so happy it's full.",
        storyText: "You go to the kitchen to prepare some food",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoDishes",
        text: "Do The Dishes",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You have no dishes that are clean",
        resolutionText: "Your dishes are so happy they are clean.",
        storyText: "You grab your sponge to do the dishes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "FillDishSoap",
        text: "Fill Dish Soap",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize you are out of dish soap",
        resolutionText: "Your dish soap is so happy to exist.",
        storyText: "You go to refill your dish soap",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetGroceries",
        text: "Get Groceries",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You open the refrigerator and realize you have no food",
        resolutionText: "Your refrigerator is so happy to be full",
        storyText: "You walk to the store to buy groceries",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PickUpTrash",
        text: "Pick Up Trash",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You hear the cats knock over the trash can",
        resolutionText: "Your trash can is so happy to be upright.",
        storyText: "You go to clean up the mess",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "DoHomework",
        text: "Do Homework",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You remember you have Game 251 homework due tonight",
        resolutionText: "The professor is so happy you completed your homework.",
        storyText: "You start up your computer to work on your homework",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TPSReport",
        text: "Complete The TPS Report",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You realize you never put the new coversheet on the TPS report you submitted at work",
        resolutionText: "Your TPS report is so happy to have a coversheet.",
        storyText: "You go to add the coversheet to the report",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TakeShower",
        text: "Take A Shower",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You smell a foul odor and realize it's you",
        resolutionText: "Your nose is so happy you're clean.",
        storyText: "You turn on the shower to let the water heat up",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GetDressed",
        text: "Get Dressed",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You look down and realize you're still wearing your pajamas, the ones with the rubber duckies",
        resolutionText: "Your body misses its comfortable uniform but it will manage.",
        storyText: "You go to the closet to pick out an outfit",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "BrushTeeth",
        text: "Brush Teeth",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your teeth are feeling a little grimy",
        resolutionText: "Your teeth are so happy to be brushed.",
        storyText: "You grab your toothbrush and put on some toothpaste",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "StyleHair",
        text: "Style Hair",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You realize you have bed head",
        resolutionText: "Your hair is so happy to be styled.",
        storyText: "You find your comb and work wonders with your hair",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "WalkDog",
        text: "Walk The Dog",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You hear your dog whining",
        resolutionText: "Your dog is so happy to be outside.",
        storyText: "You grab the leash to take the dog for a walk",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "GoRun",
        text: "Go For A Run",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You realize it's been a few days since you last worked out",
        resolutionText: "Your body is so happy to be alive.",
        storyText: "You put on your workout clothes and get ready for a run",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "ClipNails",
        text: "Clip Nails",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "Your nails are getting long and driving you crazy...you need to clip them",
        resolutionText: "Your nails feel so tidy and presentable.  They can't wait to go out in public and show off.",
        storyText: "You grab the clippers from the bathroom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "SendBdayCard",
        text: "Send Bday Card",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "Your nephew's birthday is coming up and you need to send him a card",
        resolutionText: "You're so proud of yourself for sending it before his birthday.",
        storyText: "You get a card from the desk",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "PayBills",
        text: "Pay Bills",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You need to pay the bills",
        resolutionText: "You say goodbye to some of your earnings, but your earnings don't reply.  That's so impolite!  Maybe it's for the best that they're leaving.",
        storyText: "You head towards your computer",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "ResearchLifeHacks",
        text: "Research Life Hacks",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Things would be so much better if you could be more efficient with your time, so you need to research life hacks",
        resolutionText: "You feel so much better knowing that you can rub a walnut on furniture to cover up dings, although you feel terrible for wasting 10 minutes.",
        storyText: "You grab your phone to do some high quality research",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "StartJournaling",
        text: "Start Journaling",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You know there are proven benefits to journaling.  You just need to start and now is a great time",
        resolutionText: "Your journal is so happy that you've shared your thoughts and feelings with it.  That's almost enough for it to forget about the five years you ignored it completely.",
        storyText: "You dig your journal out of the closet",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoLaundry",
        text: "Do Laundry",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "A mountain of laundry is piling up threatening to bury you in an avalanche",
        resolutionText: "You put away the last of your laundry then survey the pile of stuff you found while sorting throught it...a missing earbud, some mints, $2.36 in cash, and a monocle (no idea where that came from, but it'll be awesome for parties).",
        storyText: "You gather up all the dirty laundry",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "BuyTickets",
        text: "Buy Tickets",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your neice is in her high school's drama club production of 'Give my Regards to Broadway' and you need to buy tickets",
        resolutionText: "Your wallet is happy to be a little lighter.  You and your wallet don't always see eye-to-eye.",
        storyText: "You grab your phone",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TwiddleThumbs",
        text: "Twiddle Thumbs",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize that you've never actually twiddled your thumbs and you feel like it's something you should do at least once in your life",
        resolutionText: "Your thumbs are not sure how they feel.  You get your bucket list and check it off!",
        storyText: "You take a deep breath and prepare yourself",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {    
        name: "BuyGift",
        text: "Buy Gift for Dad",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "Your dad's birthday is coming up and you need to buy him a gift",
        resolutionText: "You're terrible at gift giving, but you settle on a heart-felt, traditional gift...a t-shirt with a progress bar that says 'Fart Loading'.  This has to go over better than the five pound gummy bear you got him last year.",
        storyText: "You start browsing online",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "ChangeSheets",
        text: "Change Sheets",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "It's time to change the sheets",
        resolutionText: "Your sheets tell you that clean sheets day is the best and you agree with them!",
        storyText: "You start toward the bedroom",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "RegisterToVote",
        text: "Register To Vote",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "You realize that you haven't registered to vote for the next election",
        resolutionText: "You submit the online paperwork and feel motivated to learn about the issues and join the political discourse in a respectful and productive manner while rejecting identify politics, misinformation, and polarization",
        storyText: "You start looking for the registration website for your state",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "DoTaxes",
        text: "Do Taxes",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You need to file your taxes",
        resolutionText: "Your secret bureaucratic urges have been sated for a year.",
        storyText: "You start to collect all the documents you need",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "ChangeLightBulb",
        text: "Change Lightbulb",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "One of your lightbulbs has gone out and needs changing.  Incidentally that's how you feel today",
        resolutionText: "The new lightbulb is so happy its practically glowing...oh, wait, yeah.",
        storyText: "You go to the closet to grab the new lightbulb",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "CleanBathroom",
        text: "Clean Bathroom",
        time: 60,
        timeLeft: 60,
        visited: false,
        status: "incomplete",
        stimText: "You need to clean the bathroom",
        resolutionText: "Your bathroom is so clean it actually squeaks, which startles you but you pretend like it didn't in case anyone was watching",
        storyText: "You gear up for the battle against grime and soap scum",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "ScoopLitter",
        text: "Scoop Litter",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "The litter boxes need to be scooped",
        resolutionText: "Your litter boxes have so much more energy now...they were a litte pooped earlier.",
        storyText: "You prepare yourself mentally for one of your favorite tasks",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
     {
        name: "CountChickens",
        text: "Count Chickens",
        time: 10,
        timeLeft: 10,
        visited: false,
        status: "incomplete",
        stimText: "Your chickens are about to hatch, so you need to count them",
        resolutionText: "Your chickens are so happy to have a numerical designator.",
        storyText: "You head toward the door",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "CheckMail",
        text: "Check The Mail",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You need to check the mail",
        resolutionText: "Your mail is happy to finally be done with its long journey.",
        storyText: "You go to put on your shoes",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "Listen",
        text: "Listen to Jimmy Buffett",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You're in the mood for a Jimmy Buffett song",
        resolutionText: "You sing along with one of your favorite lyrics 'If we weren't all crazy, we would go insane!'.",
        storyText: "You open your music app",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
        {
        name: "MakeAppt",
        text: "Make Appointment",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You remember you need to make a doctor's appointment for that random back pain you started having",
        resolutionText: "Your back is so happy you made an appointment.",
        storyText: "You grab your phone to look up the number, wondering if you're just getting old",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "TextFriend",
        text: "Text Your Friend",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You realize it's been months since you talked to your bestie",
        resolutionText: "Your bestie is so happy to hear from you.",
        storyText: "You open your messaging app to text your friend",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "MakeBed",
        text: "Make Your Bed",
        time: 5,
        timeLeft: 5,
        visited: false,
        status: "incomplete",
        stimText: "You notice your sheets are all tangled in a pile on the floor.  Must have been rough night",
        resolutionText: "Your bed is so happy to be made.",
        storyText: "You bend over to pick up the sheets",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "CleanMess",
        text: "Clean Up Mess",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You come across one of the many projects you started and never finished, which pretty much looks like a cardboard recycling bin threw up on your floor",
        resolutionText: "Your mess is so happy to be picked up.",
        storyText: "You start to collect the cardboard, duct tape, scissors and...is that a googly eye?",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    },
    {
        name: "VacuumFloor",
        text: "Vacuum The Floor",
        time: 20,
        timeLeft: 20,
        visited: false,
        status: "incomplete",
        stimText: "You dropped a box of crackers all over the floor and it needs vacuuming",
        resolutionText: "Your floor is so happy to be vacuumed.",
        storyText: "You go to the closet to pull out your vacuum",
        xPos: 0,
        yPos: 0,
        deg: 0,
        color: "#ffc"
    }
]
